#!/bin/bash

#Check if is Arch based System
#Install package: xorg, xorg-xinit nano vim opera python python-pip.
echo "Pc username:"
read username

sudo /bin/pacman -S xorg xorg-xinit nano vim opera python python-pip ninja cmake tk qt6-tools qt6 gpsd --noconfirm


#Python packages

/bin/pip install Tk


#Continue if last command finished with no errors.

    #Configuring xinitrc
sudo su << EOF
head -n -5 /etc/X11/xinit/xinitrc > /home/$username/.xinitrc
sudo echo " python app.py" >> /home/$username/.xinitrc
EOF


/bin/echo "startx" >> ~/.bashrc


 cd /etc/systemd/system/
sudo mkdir getty@tty1.service.d
 cd getty@tty1.service.d
 sudo su << EOF
echo "[Service]
Type=simple
ExecStart=
ExecStart=-/sbin/agetty --autologin $username --noclear %I 38400 linux" > override.conf
EOF
cd ~
sudo echo "#Startx Automatically
if [[ -z "$DISPLAY" ]] && [[ $(tty) = /dev/tty1 ]]; then
. startx
logout
fi" >> ~/.profile

#draft
#Stellarium
cd
/bin/git clone https://aur.archlinux.org/calcmysky.git
cd calcmysky/
/bin/makepkg -si --noconfirm
cd ..
sudo /bin/rm -r calcmysky/

cd
/bin/git clone https://aur.archlinux.org/stellarium.git 
cd stellarium/
/bin/gpg --recv-keys 9380E47C0374E169
/bin/makepkg -si --noconfirm
cd ..
sudo /bin/rm -r stellarium/

#GaiaSky
cd
/bin/git https://aur.archlinux.org/gaiasky.git
cd gaiasky/
/bin/makepkg -si --noconfirm
cd ..
sudo /bin/rm -r gaiasky

#Celestia
cd
/bin/git https://aur.archlinux.org/celestia.git
cd celestia/
/bin/makepkg -si --noconfirm
cd ..
sudo /bin/rm -r celestia
