#!/bin/bash

#Check if is Arch based System
#Install package: xorg, xorg-xinit nano vim opera python python-pip.

if [ -d /etc/pacman.d ]
then
    sudo /bin/pacman -S xorg xorg-xinit nano vim opera python python-pip ninja cmake qt6-tools qt6 gpsd --noconfirm
fi

#Python packages
if [ $? -eq 0 ]
then
    /bin/pip install Tk
fi

#Continue if last command finished with no errors.
if [ $? -eq 0 ]
then
    #Configuring xinitrc
    sudo /bin/head -n -5 /etc/X11/xinit/xinitrc > ~/.xinitrc
    sudo /bin/echo " python app.py" >> ~/.xinitrc
fi

/bin/echo "startx" >> ~/.bashrc

/bin/git clone https://github.com/mariananghel05/temp
/bin/cp temp/* ~/
sudo /bin/rm -r temp


#draft
/bin/cd
/bin/git clone https://aur.archlinux.org/calcmysky.git
/bin/cd calcmysky/
/bin/makepkg -si --noconfirm
/bin/cd ..
sudo /bin/rm -r calcmysky/

/bin/git clone https://aur.archlinux.org/stellarium.git 
/bin/cd stellarium/
/bin/gpg --recv-keys 9380E47C0374E169
/bin/makepkg -si --noconfirm
/bin/cd ..
sudo /bin/rm -r stellarium/



