#!/bin/bash

#Check if is Arch based System
#Install package: xorg, xorg-xinit nano vim opera python python-pip.
echo "Pc username:"
read username

if [ -d /etc/pacman.d ]
then
    sudo /bin/pacman -S xorg xorg-xinit nano vim opera python python-pip ninja cmake tk qt6-tools qt6 gpsd --noconfirm
fi

#Python packages
if [ $? -eq 0 ]
then
    /bin/pip install Tk
fi

#Continue if last command finished with no errors.
if [ $? -eq 0 ]
then
    #Configuring xinitrc
    sudo touch ~/.xinitrc
    sudo /bin/head -n -5 /etc/X11/xinit/xinitrc > ~/.xinitrc
    sudo /bin/echo " python app.py" >> ~/.xinitrc
fi

/bin/echo "startx" >> ~/.bashrc


#draft
cd
/bin/git clone https://aur.archlinux.org/calcmysky.git
cd calcmysky/
/bin/makepkg -si --noconfirm
cd ..
sudo /bin/rm -r calcmysky/

/bin/git clone https://aur.archlinux.org/stellarium.git 
cd stellarium/
/bin/gpg --recv-keys 9380E47C0374E169
/bin/makepkg -si --noconfirm
cd ..
sudo /bin/rm -r stellarium/

cd /etc/systemd/system/
/bin/mkdir getty@tty1.service.d
cd getty@tty1.service.d
echo "[Service]
Type=simple
ExecStart=
ExecStart=-/sbin/agetty --autologin $username --noclear %I 38400 linux" > override.conf

cd ~
echo "#Startx Automatically
if [[ -z "$DISPLAY" ]] && [[ $(tty) = /dev/tty1 ]]; then
. startx
logout
fi" >> ~/.profile




