#!/bin/bash

#Check if is Arch based System
#Install package: xorg, xorg-xinit nano vim opera python python-pip.

if [ -d /etc/pacman.d ]
then
    sudo /bin/pacman -S xorg xorg-xinit nano vim opera python python-pip ninja cmake qt6-tools qt6 gpsd --noconfirm
fi

#Python packages
if [ $? -eq 0 ]
then
    pip install Tk
fi

#Continue if last command finished with no errors.
if [ $? -eq 0 ]
then
    #Configuring xinitrc
    sudo head -n -5 /etc/X11/xinit/xinitrc > ~/.xinitrc
    sudo echo " python app.py" >> ~/.xinitrc
fi

echo "startx" >> ~/.bashrc

#draft
cd
git clone https://aur.archlinux.org/calcmysky.git
cd calcmysky/
makepkg -si --noconfirm
cd ..
sudo rm -r calcmysky/

git clone https://aur.archlinux.org/stellarium.git 
cd stellarium/
gpg --recv-keys 9380E47C0374E169
makepkg -si --noconfirm
cd ..
sudo rm -r stellarium/



